### ISSUE TITLE
Cannot run inferece_demo.ipynb (UnboundLocalError: local variable 'padded_img' referenced before assignment)

### ISSUE THREAD

**Issue by bpmsilva** [open-mmlab/mmdetection#2808]
**Describe the bug**/**Reproduction**
After I build the docker image, I try to run the inferece_demo.ipynb, but it doesn't work. I get the follwing error: `UnboundLocalError: local variable 'padded_img' referenced before assignment`

**Did you make any modifications on the code or config? Did you understand what you have modified?**
Yes, I modified the `config_file` variable from `'../configs/faster_rcnn_r50_fpn_1x_coco.py'` to `'../configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'` and the checkpoint_file to include the correct path.

**Environment**
```
sys.platform: linux
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: Tesla K80
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.2.0
MMCV: 0.5.5
MMDetection: 2.0.0+9f8c002
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.1
```

**Error traceback**
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-4-4d78d4937daf> in <module>
      1 # test a single image
      2 img = 'demo.jpg'
----> 3 result = inference_detector(model, img)

/mmdetection/mmdet/apis/inference.py in inference_detector(model, img)
     82     # prepare data
     83     data = dict(img=img)
---> 84     data = test_pipeline(data)
     85     data = collate([data], samples_per_gpu=1)
     86     if next(model.parameters()).is_cuda:

/mmdetection/mmdet/datasets/pipelines/compose.py in __call__(self, data)
     23     def __call__(self, data):
     24         for t in self.transforms:
---> 25             data = t(data)
     26             if data is None:
     27                 return None

/mmdetection/mmdet/datasets/pipelines/test_aug.py in __call__(self, results)
     23                 _results['scale'] = scale
     24                 _results['flip'] = flip
---> 25                 data = self.transforms(_results)
     26                 aug_data.append(data)
     27         # list of dict to dict of list

/mmdetection/mmdet/datasets/pipelines/compose.py in __call__(self, data)
     23     def __call__(self, data):
     24         for t in self.transforms:
---> 25             data = t(data)
     26             if data is None:
     27                 return None

/mmdetection/mmdet/datasets/pipelines/transforms.py in __call__(self, results)
    303 
    304     def __call__(self, results):
--> 305         self._pad_img(results)
    306         self._pad_masks(results)
    307         self._pad_seg(results)

/mmdetection/mmdet/datasets/pipelines/transforms.py in _pad_img(self, results)
    288                     results[key], self.size_divisor, pad_val=self.pad_val)
    289             results[key] = padded_img
--> 290         results['pad_shape'] = padded_img.shape
    291         results['pad_fixed_size'] = self.size
    292         results['pad_size_divisor'] = self.size_divisor

UnboundLocalError: local variable 'padded_img' referenced before assignment
```

**Comment by CarryHJR** [comment]
i meet the error too

**Comment by ifzhang** [comment]
Same error too.

**Comment by fxlong** [comment]
Same error too.

**Comment by hellock** [comment]
You may update to the latest version and this error should have been fixed.

**Comment by ifzhang** [comment]
@hellock  It works! Thank you very much.

**Comment by r376533** [comment]
@hellock 
Sorry I'm New for mmdetection
I dont know how to update and what should i commend?
please~

**Comment by kbiyani33** [comment]
Hello, my model and MMDetection code base is at the latest version (model 2.0.0). I am still getting this error. Can someone suggest what am I supposed to do? Thanks!!

**Comment by bpmsilva** [comment]
@kbiyani33,
This is just a guess, but, if you are on a docker image, build it again. If you're not, go through the installation procedure

**Comment by kbiyani33** [comment]
@bpmsilva Thanks for you response. I was on a docker image and rebuilding MMDetection from scratch had worked me. Thanks.

**Comment by NygmaLin** [comment]
@hellock hello,I met the same error in mmdet2.0, I don't know if this error has been fixed recently .And i'm trying to update my mmdet version.But i have no idea that if l have to train my model again or the model is compatible in the these mmdet versions.

**Comment by xvjiarui** [comment]
Hi @NygmaLin 
You don't need to train your model again if your model is trained under 2.0. 
If you are using 1.x model, there will be a little performance drop due to the coordinate system change.
