### ISSUE TITLE
DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by JosianeUwineza** [open-mmlab/mmdetection#7118]
While running single_gpu_test.py, I got this error :

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
load checkpoint from local path: /media/josi/5CEAB0FEEAB0D58C/mmdetection_/results_detr/latest.pth
[                                                  ] 0/130, elapsed: 0s, ETA:{'img_metas': [DataContainer([[{'filename': '/media/josi/5CEAB0FEEAB0D58C/Dataset/blue_phantom/prepared/test/images/annotations/img_1625131848149.jpg', 'ori_filename': 'img_1625131848149.jpg', 'ori_shape': (360, 640, 3), 'img_shape': (750, 1333, 3), 'pad_shape': (750, 1333, 3), 'scale_factor': array([2.0828125, 2.0833333, 2.0828125, 2.0833333], dtype=float32), 'flip': False, 'flip_direction': None, 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}}, {'filename': '/media/josi/5CEAB0FEEAB0D58C/Dataset/blue_phantom/prepared/test/images/annotations/img_1625131779745.jpg', 'ori_filename': 'img_1625131779745.jpg', 'ori_shape': (360, 640, 3), 'img_shape': (750, 1333, 3), 'pad_shape': (750, 1333, 3), 'scale_factor': array([2.0828125, 2.0833333, 2.0828125, 2.0833333], dtype=float32), 'flip': False, 'flip_direction': None, 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}}]])], 'img': [tensor([[[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          ...,
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

         [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          ...,
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],

         [[-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          ...,
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044]]],

        [[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          ...,
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

         [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          ...,
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],

         [[-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          ...,
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044]]]])]}
Traceback (most recent call last):
  File "config_files/newf_detr_res50.py", line 98, in <module>
    outputs = single_gpu_test(model, data_loader, out_dir= './results_phantom' )
  File "/media/josi/5CEAB0FEEAB0D58C/mmdetection/mmdet/apis/test.py", line 29, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/josi/anaconda3/envs/mmdetect/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/josi/anaconda3/envs/mmdetect/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/media/josi/5CEAB0FEEAB0D58C/mmdetection/mmdet/models/detectors/base.py", line 176, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/media/josi/5CEAB0FEEAB0D58C/mmdetection/mmdet/models/detectors/base.py", line 140, in forward_test
    img_meta[batch_size]['batch_input_shape'] = tuple(img.size()[-2:])
TypeError: 'DataContainer' object is not subscriptable.

This is my configuration file:
# inferencing with  single_gpu_test
cfg = Config.fromfile('./configs/detr/detr_r50_8x2_150e_coco.py')
cfg.dataset_type = 'CocoDataset'
cfg.classes = ("cystic_mass", "solid_mass")
cfg.model.bbox_head.num_classes = 2

# Training data  
PREFIX = '/media/josi/5CEAB0FEEAB0D58C/Dataset/blue_phantom/prepared/'
cfg.data.train.img_prefix = PREFIX + 'train/images/annotations/'
cfg.data.train.classes = cfg.classes
cfg.data.train.ann_file = PREFIX + 'train/annotations/instances_annotations.json'
cfg.data.train.type = 'CocoDataset'

# Validation data
cfg.data.val.img_prefix = PREFIX + 'valid/images/annotations/'
cfg.data.val.classes = cfg.classes
cfg.data.val.ann_file = PREFIX + 'valid/annotations/instances_annotations.json'
cfg.data.val.type = 'CocoDataset' 

# Testing data
cfg.data.test.img_prefix = PREFIX + 'test/images/annotations/'
cfg.data.test.classes = cfg.classes
cfg.data.test.ann_file = PREFIX + 'test/annotations/instances_annotations.json'
cfg.data.test.type = 'CocoDataset'

#cfg.data.test.pipeline = get_loading_pipeline(cfg.data.train.pipeline)
# build data and initialize detector
#cfg.work_dir = "./outputs_phantom"
datasets = build_dataset(cfg.data.test)
data_loader = build_dataloader(
        datasets,
        samples_per_gpu=2,
        workers_per_gpu=1,
        dist=False,
        shuffle=False)
cfg.model.train_cfg = None    
model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
model.CLASSES = [datasets][0].CLASSES

checkpoint_file = '/media/josi/5CEAB0FEEAB0D58C/mmdetection_/results_detr/latest.pth'
checkpoint = load_checkpoint(model, checkpoint_file, map_location='cuda')
#data['img_metas'][0] = data['img_metas'][0].data[0]
outputs = single_gpu_test(model, data_loader, out_dir= './results_phantom' )
out_file = './results_phantom/result.pkl'
mmcv.dump(outputs, out_file)

Any help will be much appreciated

**Comment by JosianeUwineza** [comment]
This error is coming from mmdetection/models/detectors/base.py, line 134 object is not subscriptable, is a way to fix it?

**Comment by jbwang1997** [comment]
It seems the same issues as https://github.com/open-mmlab/mmdetection/issues/4737.

You can try to upgrade the version of mmcv or change the version of pytorch.

**Comment by JosianeUwineza** [comment]
Thank you @jbwang1997  the issue was solved

**Comment by siddharthKatageri** [comment]
Hi @JosianeUwineza, how did you solve this issue?
Thanks.

**Comment by mexicantexan** [comment]
@JosianeUwineza how did you solve the issue? was it adjusting your version of pytorch?

**Comment by Jacqueline121** [comment]
solved by upgrading mmcv to 1.7.0

**Comment by chuzunheng** [comment]
> 谢谢@jbwang1997 问题已解决

I have the same problem, how can I solve it

**Comment by chuzunheng** [comment]
> 谢谢@jbwang1997 问题已解决



> 这个错误来自mmdetection/models/ detectors/base.py，第134行对象不可下标，有办法修复吗？

I have the same problem, how can I solve it

**Comment by Solacex** [comment]
Hello, I am using mmcv-full 1.5.3 which actually fix the mentioned issue, https://github.com/open-mmlab/mmcv/pull/882. But this error still occurs.
